### ISSUE TITLE
[Request] Snippets for Sublime Text

### ISSUE THREAD

**Issue by some-username-here1** [dangreene0/tf2-vscript-snippets#2]
It would be nice if the vscript snippets made for Visual Studio Code would be made for Sublime Text as well, as its one of few text editor programs that is natively supported for Linux.

**Comment by ZacharyTalis** [comment]
Check out the [new instructions](https://github.com/ZacharyTalis/tf2-vscript-snippets#installing-snippets-into-sublime-text), and let me know if you run into any issues :)

I'm on Linux, but don't plan on keeping Sublime Text installed. You can run [this script](https://github.com/ZacharyTalis/tf2-vscript-snippets/blob/main/convert-to-sublime.py) to convert `squirrel.json` into text for `tf2-snippets.sublime-completions`.
