### ISSUE TITLE
[Feature Request] upload VSIX files to releases tab

### ISSUE THREAD

**Issue by treacherousfiend** [dangreene0/tf2-vscript-snippets#7]
For people using forks of VSCode with microsoft's servers stripped out, like VSCodium, there's no easy way to install the extension outside of building it yourself. Providing VSIX files will allow manual installations.

**Comment by sour-dani** [comment]
Here you go:
https://github.com/dangreene0/tf2-vscript-snippets/releases/tag/1.0.1

I will continue uploading the extension there but you can always [download the extension from it's marketplace listing](https://marketplace.visualstudio.com/items?itemName=SourDani.tf2-vscript-snippets) via the Resources side panel or [add the VS Marketplace back to your fork.](https://www.flypenguin.de/2023/02/26/use-vscodium-with-microsofts-proprietary-marketplace/)

Thanks for the suggestion.

**Comment by sour-dani** [comment]
Update, I will now start uploading the extension to [Open VSX](https://open-vsx.org/extension/SourDani/tf2-vscript-snippets)

> Here you go: https://github.com/dangreene0/tf2-vscript-snippets/releases/tag/1.0.1
> 
> I will continue uploading the extension there but you can always [download the extension from it's marketplace listing](https://marketplace.visualstudio.com/items?itemName=SourDani.tf2-vscript-snippets) via the Resources side panel or [add the VS Marketplace back to your fork.](https://www.flypenguin.de/2023/02/26/use-vscodium-with-microsofts-proprietary-marketplace/)
> 
> Thanks for the suggestion.
