### ISSUE TITLE
Add snippets for each game event

### ISSUE THREAD

**Issue by WereTech** [dangreene0/tf2-vscript-snippets#8]
It would be useful to have snippets for each game event without needing to look through the alliedmod wiki's list of events. I have made two files for this already, one for vscode and another for sublime as it's an option in this repo. They are missing descriptions, however this is due to these events just not having good documentation if at all (perhaps what the events will return would be good here?), so if someone else knows what all of these events do, they may modify these for the repo.

[gameeventslist.txt](https://github.com/dangreene0/tf2-vscript-snippets/files/13328824/gameeventslist.txt)
[gameeventslist_sublime.txt](https://github.com/dangreene0/tf2-vscript-snippets/files/13328825/gameeventslist_sublime.txt)

**Comment by sour-dani** [comment]
Thanks for this list! This is definitely a planned feature. The current way the OnGameEvent works just wasn't gonna cut it

I'll add this very soon! Thanks again for the list!

**Comment by sour-dani** [comment]
> It would be useful to have snippets for each game event without needing to look through the alliedmod wiki's list of events. I have made two files for this already, one for vscode and another for sublime as it's an option in this repo. They are missing descriptions, however this is due to these events just not having good documentation if at all (perhaps what the events will return would be good here?), so if someone else knows what all of these events do, they may modify these for the repo.
> 
> [gameeventslist.txt](https://github.com/dangreene0/tf2-vscript-snippets/files/13328824/gameeventslist.txt) [gameeventslist_sublime.txt](https://github.com/dangreene0/tf2-vscript-snippets/files/13328825/gameeventslist_sublime.txt)

Added and Credited in commit 65bc884! This will be included in the next update that will be [available later today](https://github.com/dangreene0/tf2-vscript-snippets/releases/tag/1.0.2).
